# Generated by Django 5.0.2 on 2024-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_wharehouse_warehouse_rename_war_item_wh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
