# Generated by Django 5.0.2 on 2024-02-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='units',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.units'),
            preserve_default=False,
        ),
    ]
