# Generated by Django 5.0.2 on 2024-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_amount_item_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
